
Xvnc Free Edition 4.1.1 - built Feb 25 2015 23:02:21
Copyright (C) 2002-2005 RealVNC Ltd.
See http://www.realvnc.com for information on VNC.
Underlying X server release 40300000, The XFree86 Project, Inc


Fri Jan 10 10:07:49 2020
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on port 5919
 vncext:      created VNC server for screen 0
error opening security policy file /etc/X11/xserver/SecurityPolicy
Could not init font path element /usr/X11R6/lib/X11/fonts/Type1/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/Speedo/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/misc/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/75dpi/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/100dpi/, removing from list!
Could not init font path element /usr/share/fonts/X11/75dpi/, removing from list!
Could not init font path element /usr/share/fonts/X11/100dpi/, removing from list!
xrdb: No such file or directory
xrdb: can't open file '/home/is28/yablokova28/.Xresources'
/usr/bin/startxfce4: X server already running on display :19
gpg-agent[30527]: WARNING: "--write-env-file" is an obsolete option - it has no effect
gpg-agent: a gpg-agent is already running - not starting a new one

(xfce4-session:30517): xfce4-session-WARNING **: 10:07:52.675: gpg-agent returned no PID in the variables

(xfce4-session:30517): xfce4-session-WARNING **: 10:07:52.680: xfsm_manager_load_session: Something wrong with /home/is28/yablokova28/.cache/sessions/xfce4-session-virt-1:19, Does it exist? Permissions issue?

(xfwm4:30531): xfwm4-WARNING **: 10:07:53.279: The display does not support the XRender extension.

(xfwm4:30531): xfwm4-WARNING **: 10:07:53.280: The display does not support the XComposite extension.

(xfwm4:30531): xfwm4-WARNING **: 10:07:53.280: The display does not support the XDamage extension.

(xfwm4:30531): xfwm4-WARNING **: 10:07:53.280: The display does not support the XFixes extension.

(xfwm4:30531): xfwm4-WARNING **: 10:07:53.280: Compositing manager disabled.
(uint32 1,)

** (light-locker:30541): ERROR **: 10:07:54.027: Environment variable XDG_SESSION_PATH not set. Is LightDM running?

(polkit-gnome-authentication-agent-1:30552): GLib-CRITICAL **: 10:07:54.050: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:30552): polkit-gnome-1-WARNING **: 10:07:54.051: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
xfwm4-Message: 10:07:54.989: Unsupported keyboard modifier '<Super>Tab'

(xfsettingsd:30540): xfsettingsd-CRITICAL **: 10:07:55.236: RANDR extension is too old, version 1.1. Display settings won't be applied.
Xlib:  extension "XInputExtension" missing on display ":19.0".

(xfsettingsd:30540): xfsettingsd-CRITICAL **: 10:07:55.242: XI is not present.

(xfsettingsd:30540): xfsettingsd-CRITICAL **: 10:07:55.246: Failed to initialize the Xkb extension.

(xfsettingsd:30540): xfsettingsd-CRITICAL **: 10:07:55.247: Failed to initialize the Accessibility extension.
xfwm4-Message: 10:07:55.612: Unsupported keyboard modifier '<Super>Tab'

(nm-applet:30652): Gtk-WARNING **: 10:07:55.735: Can't set a parent on widget which has a parent

(nm-applet:30652): Gdk-CRITICAL **: 10:07:55.940: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

Fri Jan 10 10:08:07 2020
 Connections: accepted: 0.0.0.0::58888
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)

Fri Jan 10 10:08:10 2020
 VNCSConnST:  Server default pixel format depth 16 (16bpp) little-endian rgb565
 VNCSConnST:  Client pixel format depth 16 (16bpp) little-endian rgb565

(Thunar:30537): Gdk-WARNING **: 10:08:16.038: gdk_window_set_icon_list: icons too large
/usr/lib/python3/dist-packages/blueman/plugins/applet/AppIndicator.py:8: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as girAppIndicator
ERROR:dbus.proxies:Introspect error on org.bluez:/org/bluez: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.15296" (uid=1290 pid=30642 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)
ERROR:dbus.proxies:Introspect error on org.bluez:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.15296" (uid=1290 pid=30642 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)
ERROR:dbus.proxies:Introspect error on org.bluez:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.15296" (uid=1290 pid=30642 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)

(wrapper-1.0:30714): Gdk-WARNING **: 10:08:21.514: /build/gtk+2.0-AoeliP/gtk+2.0-2.24.32/gdk/x11/gdkdrawable-x11.c:952 drawable is not a pixmap or window

(wrapper-1.0:30714): Gdk-WARNING **: 10:08:21.515: /build/gtk+2.0-AoeliP/gtk+2.0-2.24.32/gdk/x11/gdkdrawable-x11.c:952 drawable is not a pixmap or window

(Thunar:30537): Gdk-WARNING **: 10:08:27.953: gdk_window_set_icon_list: icons too large

(polkit-gnome-authentication-agent-1:30552): polkit-gnome-1-WARNING **: 10:08:30.988: Couldn't open user icon: Failed to open file '/home/adom/.face': No such file or directory

(polkit-gnome-authentication-agent-1:30552): polkit-gnome-1-WARNING **: 10:08:30.990: Couldn't open user icon: Failed to open file '/home/test/.face': No such file or directory
Gtk-Message: 10:08:31.046: GtkDialog mapped without a transient parent. This is discouraged.

(Thunar:30537): GLib-GIO-CRITICAL **: 10:08:34.672: g_file_hash: assertion 'G_IS_FILE (file)' failed

(Thunar:30537): GLib-GIO-CRITICAL **: 10:08:34.673: g_file_query_info_async: assertion 'G_IS_FILE (file)' failed

(Thunar:30537): GLib-GObject-CRITICAL **: 10:08:34.673: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(polkit-gnome-authentication-agent-1:30552): polkit-gnome-1-WARNING **: 10:08:35.896: Couldn't open user icon: Failed to open file '/home/adom/.face': No such file or directory

(polkit-gnome-authentication-agent-1:30552): polkit-gnome-1-WARNING **: 10:08:35.897: Couldn't open user icon: Failed to open file '/home/test/.face': No such file or directory
Gtk-Message: 10:08:35.904: GtkDialog mapped without a transient parent. This is discouraged.

(Thunar:30537): GLib-GIO-CRITICAL **: 10:08:38.581: g_file_hash: assertion 'G_IS_FILE (file)' failed

(Thunar:30537): GLib-GIO-CRITICAL **: 10:08:38.581: g_file_query_info_async: assertion 'G_IS_FILE (file)' failed

(Thunar:30537): GLib-GObject-CRITICAL **: 10:08:38.581: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(Thunar:30537): Gdk-WARNING **: 10:10:57.083: gdk_window_set_icon_list: icons too large

(polkit-gnome-authentication-agent-1:30552): polkit-gnome-1-WARNING **: 10:11:08.050: Couldn't open user icon: Failed to open file '/home/adom/.face': No such file or directory

(polkit-gnome-authentication-agent-1:30552): polkit-gnome-1-WARNING **: 10:11:08.051: Couldn't open user icon: Failed to open file '/home/test/.face': No such file or directory
Gtk-Message: 10:11:08.058: GtkDialog mapped without a transient parent. This is discouraged.

(Thunar:30537): GLib-GIO-CRITICAL **: 10:11:14.373: g_file_hash: assertion 'G_IS_FILE (file)' failed

(Thunar:30537): GLib-GIO-CRITICAL **: 10:11:14.373: g_file_query_info_async: assertion 'G_IS_FILE (file)' failed

(Thunar:30537): GLib-GObject-CRITICAL **: 10:11:14.373: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(Thunar:30537): Gdk-WARNING **: 10:11:38.080: gdk_window_set_icon_list: icons too large

(Thunar:30537): Gdk-WARNING **: 10:38:59.825: gdk_window_set_icon_list: icons too large

Fri Jan 10 21:21:26 2020
 Connections: closed: 0.0.0.0::58888 (read: Connection reset by peer (104))
 SMsgWriter:  framebuffer updates 2761
 SMsgWriter:    copyRect rects 357, bytes 5712
 SMsgWriter:    hextile rects 10743, bytes 532857518
 SMsgWriter:    raw bytes equivalent 1322236364, compression ratio 2.481407
/usr/lib/ubuntu-release-upgrader/check-new-release-gtk:30: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
WARNING:root:timeout reached, exiting
/usr/share/system-config-printer/applet.py:45: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
system-config-printer-applet: failed to start NewPrinterNotification service
system-config-printer-applet: failed to start PrinterDriversInstaller service: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.15289" is not allowed to own the service "com.redhat.PrinterDriversInstaller" due to security policies in the configuration file
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 10 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 14 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 16 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 22 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 26 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 27 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 31 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 33 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 35 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 36 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 40 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 42 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 48 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 52 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 54 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 58 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 60 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 61 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 65 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 66 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 70 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 72 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 73 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 77 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 79 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 81 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 87 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 91 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 93 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 94 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 98 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 100 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 101 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 105 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 107 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 108 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 112 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 114 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 115 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 119 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 121 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 122 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 126 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 127 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 133 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 134 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 138 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 140 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 142 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 143 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 147 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 149 was not found when attempting to remove it
  GLib.source_remove (self.timer)

(xfwm4:30531): libxfce4ui-WARNING **: 00:23:38.968: ICE I/O Error

(xfwm4:30531): libxfce4ui-WARNING **: 00:23:38.969: Disconnected from session manager.
The application 'xfwm4' lost its connection to the display :19.0;
most likely the X server was shut down or you killed/destroyed
the application.
xfdesktop: Fatal IO error 4 (Interrupted system call) on X server :19.0.
