
Xvnc Free Edition 4.1.1 - built Feb 25 2015 23:02:21
Copyright (C) 2002-2005 RealVNC Ltd.
See http://www.realvnc.com for information on VNC.
Underlying X server release 40300000, The XFree86 Project, Inc


Wed Nov 27 11:51:41 2019
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on port 5907
 vncext:      created VNC server for screen 0
error opening security policy file /etc/X11/xserver/SecurityPolicy
Could not init font path element /usr/X11R6/lib/X11/fonts/Type1/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/Speedo/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/misc/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/75dpi/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/100dpi/, removing from list!
Could not init font path element /usr/share/fonts/X11/75dpi/, removing from list!
Could not init font path element /usr/share/fonts/X11/100dpi/, removing from list!
xrdb: No such file or directory
xrdb: can't open file '/home/is28/stanislavchuk28/.Xresources'
/usr/bin/startxfce4: X server already running on display :7
gpg-agent[6111]: WARNING: "--write-env-file" is an obsolete option - it has no effect
gpg-agent: a gpg-agent is already running - not starting a new one

(xfce4-session:6097): xfce4-session-WARNING **: 11:51:44.416: gpg-agent returned no PID in the variables

(xfce4-session:6097): xfce4-session-WARNING **: 11:51:44.422: xfsm_manager_load_session: Something wrong with /home/is28/stanislavchuk28/.cache/sessions/xfce4-session-virt-1:7, Does it exist? Permissions issue?

(xfwm4:6117): xfwm4-WARNING **: 11:51:44.447: The display does not support the XRender extension.

(xfwm4:6117): xfwm4-WARNING **: 11:51:44.448: The display does not support the XComposite extension.

(xfwm4:6117): xfwm4-WARNING **: 11:51:44.448: The display does not support the XDamage extension.

(xfwm4:6117): xfwm4-WARNING **: 11:51:44.448: The display does not support the XFixes extension.

(xfwm4:6117): xfwm4-WARNING **: 11:51:44.448: Compositing manager disabled.

** (light-locker:6131): ERROR **: 11:51:44.504: Environment variable XDG_SESSION_PATH not set. Is LightDM running?

(polkit-gnome-authentication-agent-1:6140): GLib-CRITICAL **: 11:51:44.522: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:6140): polkit-gnome-1-WARNING **: 11:51:44.523: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
(uint32 1,)
xfwm4-Message: 11:51:44.558: Unsupported keyboard modifier '<Super>Tab'

(xfsettingsd:6133): xfsettingsd-CRITICAL **: 11:51:44.612: RANDR extension is too old, version 1.1. Display settings won't be applied.
Xlib:  extension "XInputExtension" missing on display ":7.0".

(xfsettingsd:6133): xfsettingsd-CRITICAL **: 11:51:44.613: XI is not present.

(xfsettingsd:6133): xfsettingsd-CRITICAL **: 11:51:44.615: Failed to initialize the Xkb extension.

(xfsettingsd:6133): xfsettingsd-CRITICAL **: 11:51:44.618: Failed to initialize the Accessibility extension.
xfwm4-Message: 11:51:44.689: Unsupported keyboard modifier '<Super>Tab'

(nm-applet:6253): Gtk-WARNING **: 11:51:44.749: Can't set a parent on widget which has a parent

(nm-applet:6253): Gdk-CRITICAL **: 11:51:44.884: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

Wed Nov 27 11:51:51 2019
 Connections: accepted: 0.0.0.0::50023
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)

Wed Nov 27 11:51:56 2019
 VNCSConnST:  Server default pixel format depth 16 (16bpp) little-endian rgb565
 VNCSConnST:  Client pixel format depth 16 (16bpp) little-endian rgb565
/usr/lib/python3/dist-packages/blueman/plugins/applet/AppIndicator.py:8: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as girAppIndicator
ERROR:dbus.proxies:Introspect error on org.bluez:/org/bluez: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.698" (uid=1282 pid=6224 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)
ERROR:dbus.proxies:Introspect error on org.bluez:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.698" (uid=1282 pid=6224 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)
ERROR:dbus.proxies:Introspect error on org.bluez:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.698" (uid=1282 pid=6224 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)

(wrapper-1.0:6316): Gdk-WARNING **: 11:52:03.852: /build/gtk+2.0-AoeliP/gtk+2.0-2.24.32/gdk/x11/gdkdrawable-x11.c:952 drawable is not a pixmap or window

Wed Nov 27 12:11:49 2019
 XserverDesktop: Added unknown keysym 0x6f7 to keycode 255
xfwm4-Message: 12:11:49.929: Unsupported keyboard modifier '<Super>Tab'

Wed Nov 27 12:11:52 2019
 XserverDesktop: Added unknown keysym 0x6c5 to keycode 254
xfwm4-Message: 12:11:53.185: Unsupported keyboard modifier '<Super>Tab'

Wed Nov 27 12:11:53 2019
 XserverDesktop: Added unknown keysym 0x6c4 to keycode 253
xfwm4-Message: 12:11:53.633: Unsupported keyboard modifier '<Super>Tab'
 XserverDesktop: Added unknown keysym 0x6c9 to keycode 252
 XserverDesktop: Added unknown keysym 0x6d4 to keycode 251
xfwm4-Message: 12:11:54.072: Unsupported keyboard modifier '<Super>Tab'

Wed Nov 27 12:11:54 2019
 XserverDesktop: Added unknown keysym 0x6d3 to keycode 250
xfwm4-Message: 12:11:54.681: Unsupported keyboard modifier '<Super>Tab'
 XserverDesktop: Added unknown keysym 0x6d2 to keycode 249

Wed Nov 27 12:11:55 2019
 XserverDesktop: Added unknown keysym 0x6cf to keycode 248
 XserverDesktop: Added unknown keysym 0x6cb to keycode 247
 XserverDesktop: Added unknown keysym 0xf3 to keycode 246
xfwm4-Message: 12:11:55.697: Unsupported keyboard modifier '<Super>Tab'

(gedit:15108): Gtk-WARNING **: 12:29:19.389: Calling org.xfce.Session.Manager.Inhibit failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "Inhibit" with signature "susu" on interface "org.xfce.Session.Manager" doesn't exist


(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:30:56.100:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/slovar.txt) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:30:56.100: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(gedit:15206): Gtk-WARNING **: 12:31:07.062: Calling org.xfce.Session.Manager.Inhibit failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "Inhibit" with signature "susu" on interface "org.xfce.Session.Manager" doesn't exist


(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:31:35.114:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/pxp.txt) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:31:35.114: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(gedit:15417): Gtk-WARNING **: 12:33:02.592: Calling org.xfce.Session.Manager.Inhibit failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "Inhibit" with signature "susu" on interface "org.xfce.Session.Manager" doesn't exist


(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:33:14.617:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/pxp.txt) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:33:14.617: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(gedit:15449): Gtk-WARNING **: 12:34:11.416: Calling org.xfce.Session.Manager.Inhibit failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "Inhibit" with signature "susu" on interface "org.xfce.Session.Manager" doesn't exist


(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:34:53.482:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/slovar.txt) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:34:53.482: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

Wed Nov 27 12:39:08 2019
 Connections: closed: 0.0.0.0::50023 (Clean disconnection)
 SMsgWriter:  framebuffer updates 5660
 SMsgWriter:    copyRect rects 142, bytes 2272
 SMsgWriter:    hextile rects 11342, bytes 39329447
 SMsgWriter:    raw bytes equivalent 501147184, compression ratio 12.742289
xfce4-session: Fatal IO error 11 (Resource temporarily unavailable) on X server :7.
xfwm4: Fatal IO error 11 (Resource temporarily unavailable) on X server :7.0.

(xfce4-terminal:6646): libxfce4ui-WARNING **: 11:27:39.027: ICE I/O Error

(xfce4-terminal:6646): libxfce4ui-WARNING **: 11:27:39.027: Disconnected from session manager.

(xfce4-panel:6121): libxfce4ui-WARNING **: 11:27:39.027: ICE I/O Error

(xfce4-panel:6121): libxfce4ui-WARNING **: 11:27:39.027: Disconnected from session manager.

(xfsettingsd:6133): libxfce4ui-WARNING **: 11:27:39.028: ICE I/O Error

(xfsettingsd:6133): libxfce4ui-WARNING **: 11:27:39.028: Disconnected from session manager.

(xfdesktop:6126): libxfce4ui-WARNING **: 11:27:39.028: ICE I/O Error

(xfdesktop:6126): libxfce4ui-WARNING **: 11:27:39.028: Disconnected from session manager.
xfce4-panel: Fatal IO error 11 (Resource temporarily unavailable) on X server :7.0.
xfdesktop: Fatal IO error 11 (Resource temporarily unavailable) on X server :7.0.
xfsettingsd: Fatal IO error 11 (Resource temporarily unavailable) on X server :7.0.
Thunar: Fatal IO error 11 (Resource temporarily unavailable) on X server :7.0.
Gdk-Message: 11:27:39.177: polkit-gnome-authentication-agent-1: Fatal IO error 11 (Resource temporarily unavailable) on X server :7.0.

Gdk-Message: 11:27:39.177: update-notifier: Fatal IO error 11 (Resource temporarily unavailable) on X server :7.0.

Gdk-Message: 11:27:39.177: evolution-alarm-notify: Fatal IO error 11 (Resource temporarily unavailable) on X server :7.0.

wrapper-1.0: Fatal IO error 11 (Resource temporarily unavailable) on X server :7.0.
Gdk-Message: 11:27:39.179: nm-applet: Fatal IO error 11 (Resource temporarily unavailable) on X server :7.0.

Gdk-Message: 11:27:39.179: xfce4-terminal: Fatal IO error 11 (Resource temporarily unavailable) on X server :7.0.

wrapper-1.0: Fatal IO error 11 (Resource temporarily unavailable) on X server :7.0.
Gdk-Message: 11:27:39.182: blueman-applet: Fatal IO error 11 (Resource temporarily unavailable) on X server :7.0.


(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:40:38.106:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:40:38.107: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:42:38.807:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:42:38.807: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:46:48.056:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:46:48.056: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:47:10.261:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:47:10.261: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:47:37.264:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:47:37.264: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:48:20.082:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:48:20.082: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:48:35.874:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:48:35.874: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:51:44.647:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:51:44.647: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:51:54.692:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:51:54.692: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:52:22.943:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:52:22.943: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:52:36.987:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:52:36.987: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:53:15.082:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:53:15.082: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:57:21.715:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/pxp.txt) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:57:21.715: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:58:59.842:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:58:59.842: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:59:29.612:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:59:29.612: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:00:51.181:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:00:51.181: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:01:22.562:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:01:22.562: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:02:43.818:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:02:43.818: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:03:28.192:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:03:28.192: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:04:35.501:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:04:35.501: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:05:08.647:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:05:08.647: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:05:45.130:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:05:45.130: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:06:38.458:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:06:38.458: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:07:02.471:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:07:02.471: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:07:46.288:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:07:46.289: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:08:00.130:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:08:00.130: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:08:10.522:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:08:10.522: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:09:45.033:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:09:45.033: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:10:17.787:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:10:17.787: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:11:12.237:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:11:12.237: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:11:42.637:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:11:42.637: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:12:09.931:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:12:09.931: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:12:45.303:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:12:45.303: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:13:04.553:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:13:04.553: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:13:31.425:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:13:31.425: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:13:57.700:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:13:57.700: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:14:16.807:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:14:16.807: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:14:51.793:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:14:51.793: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:15:37.624:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:15:37.624: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:16:01.321:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:16:01.321: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:16:54.596:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:16:54.596: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:17:35.627:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:17:35.627: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:20:32.775:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:20:32.775: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:21:18.375:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:21:18.375: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:22:42.646:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:22:42.646: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:22:55.360:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:22:55.360: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:26:51.636:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:26:51.636: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:27:01.769:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:27:01.770: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:27:10.612:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:27:10.612: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:30:29.644:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:30:29.644: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:31:29.135:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:31:29.135: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:32:18.714:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:32:18.714: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:32:26.585:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:32:26.585: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:33:11.534:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:33:11.534: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:34:04.121:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:34:04.121: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:34:53.599:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:34:53.599: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:35:08.181:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:35:08.181: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:35:18.718:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:35:18.718: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:37:52.584:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:37:52.584: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url
/usr/share/system-config-printer/applet.py:45: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
system-config-printer-applet: failed to start NewPrinterNotification service
system-config-printer-applet: failed to start PrinterDriversInstaller service: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.697" is not allowed to own the service "com.redhat.PrinterDriversInstaller" due to security policies in the configuration file
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 11 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 15 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 16 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 20 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 22 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 24 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 25 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 29 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 33 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 34 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 38 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 40 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 44 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 48 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 50 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 54 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 55 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 59 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 61 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 63 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 67 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 69 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 73 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 75 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 79 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 81 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 85 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 86 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 90 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 94 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 96 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 98 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 100 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 104 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 106 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 110 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 111 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 115 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 117 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 119 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 123 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 125 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 129 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 130 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 134 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 136 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 137 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 141 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 143 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 144 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 148 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 150 was not found when attempting to remove it
  GLib.source_remove (self.timer)

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:48:12.935:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:48:12.939: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:48:26.627:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:48:26.627: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:48:54.135:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/0.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:48:54.135: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:48:59.505:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/test.txt) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:48:59.505: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:53:55.355:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/slovar.txt) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:53:55.356: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:58:54.417:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/slovar.txt) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 11:58:54.417: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:04:52.440:   (Sparql buffer) Error in task 0 (file:///home/is28/stanislavchuk28/slovar.txt) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:6143): Tracker-CRITICAL **: 12:04:52.440: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 152 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 156 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 157 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 161 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 163 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 164 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 168 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 170 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 173 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 174 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 176 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 178 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 180 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 181 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 185 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 187 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 188 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 192 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 194 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 196 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 200 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 202 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 208 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 212 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 213 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 219 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 220 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 224 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 226 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 228 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 232 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 233 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 237 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 239 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 240 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 244 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 248 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 249 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 257 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 261 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 262 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 266 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 270 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 274 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 275 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 283 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 284 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 288 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 290 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 291 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 295 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 297 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 301 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 302 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 306 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 310 was not found when attempting to remove it
  GLib.source_remove (self.timer)
