
Xvnc Free Edition 4.1.1 - built Feb 25 2015 23:02:21
Copyright (C) 2002-2005 RealVNC Ltd.
See http://www.realvnc.com for information on VNC.
Underlying X server release 40300000, The XFree86 Project, Inc


Fri Dec 13 11:14:28 2019
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on port 5904
 vncext:      created VNC server for screen 0
error opening security policy file /etc/X11/xserver/SecurityPolicy
Could not init font path element /usr/X11R6/lib/X11/fonts/Type1/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/Speedo/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/misc/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/75dpi/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/100dpi/, removing from list!
Could not init font path element /usr/share/fonts/X11/75dpi/, removing from list!
Could not init font path element /usr/share/fonts/X11/100dpi/, removing from list!
xrdb: No such file or directory
xrdb: can't open file '/home/is28/konnov28/.Xresources'
/usr/bin/startxfce4: X server already running on display :4
gpg-agent[14884]: WARNING: "--write-env-file" is an obsolete option - it has no effect
gpg-agent: a gpg-agent is already running - not starting a new one

(xfce4-session:14874): xfce4-session-WARNING **: 11:14:31.531: gpg-agent returned no PID in the variables

(xfce4-session:14874): xfce4-session-WARNING **: 11:14:31.536: xfsm_manager_load_session: Something wrong with /home/is28/konnov28/.cache/sessions/xfce4-session-virt-1:4, Does it exist? Permissions issue?

(xfwm4:14888): xfwm4-WARNING **: 11:14:31.567: The display does not support the XRender extension.

(xfwm4:14888): xfwm4-WARNING **: 11:14:31.567: The display does not support the XComposite extension.

(xfwm4:14888): xfwm4-WARNING **: 11:14:31.567: The display does not support the XDamage extension.

(xfwm4:14888): xfwm4-WARNING **: 11:14:31.567: The display does not support the XFixes extension.

(xfwm4:14888): xfwm4-WARNING **: 11:14:31.567: Compositing manager disabled.

** (light-locker:14897): ERROR **: 11:14:31.588: Environment variable XDG_SESSION_PATH not set. Is LightDM running?

(polkit-gnome-authentication-agent-1:14900): GLib-CRITICAL **: 11:14:31.598: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:14900): polkit-gnome-1-WARNING **: 11:14:31.598: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
(uint32 1,)
xfwm4-Message: 11:14:31.643: Unsupported keyboard modifier '<Super>Tab'

(xfsettingsd:14899): xfsettingsd-CRITICAL **: 11:14:31.678: RANDR extension is too old, version 1.1. Display settings won't be applied.
Xlib:  extension "XInputExtension" missing on display ":4.0".

(xfsettingsd:14899): xfsettingsd-CRITICAL **: 11:14:31.678: XI is not present.

(xfsettingsd:14899): xfsettingsd-CRITICAL **: 11:14:31.679: Failed to initialize the Xkb extension.

(xfsettingsd:14899): xfsettingsd-CRITICAL **: 11:14:31.679: Failed to initialize the Accessibility extension.
xfwm4-Message: 11:14:31.745: Unsupported keyboard modifier '<Super>Tab'

(nm-applet:14997): Gtk-WARNING **: 11:14:31.813: Can't set a parent on widget which has a parent

(nm-applet:14997): Gdk-CRITICAL **: 11:14:32.064: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

Fri Dec 13 11:14:46 2019
 Connections: accepted: 0.0.0.0::50579
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)

Fri Dec 13 11:14:50 2019
 VNCSConnST:  Server default pixel format depth 16 (16bpp) little-endian rgb565
 VNCSConnST:  Client pixel format depth 16 (16bpp) little-endian rgb565
/usr/lib/python3/dist-packages/blueman/plugins/applet/AppIndicator.py:8: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as girAppIndicator
ERROR:dbus.proxies:Introspect error on org.bluez:/org/bluez: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.1831" (uid=1273 pid=14978 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)
ERROR:dbus.proxies:Introspect error on org.bluez:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.1831" (uid=1273 pid=14978 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)
ERROR:dbus.proxies:Introspect error on org.bluez:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.1831" (uid=1273 pid=14978 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)

(polkit-gnome-authentication-agent-1:14900): polkit-gnome-1-WARNING **: 11:15:03.105: Couldn't open user icon: Failed to open file '/home/adom/.face': No such file or directory

(polkit-gnome-authentication-agent-1:14900): polkit-gnome-1-WARNING **: 11:15:03.106: Couldn't open user icon: Failed to open file '/home/test/.face': No such file or directory
Gtk-Message: 11:15:03.136: GtkDialog mapped without a transient parent. This is discouraged.

(polkit-gnome-authentication-agent-1:14900): polkit-gnome-1-WARNING **: 11:15:05.786: Couldn't open user icon: Failed to open file '/home/adom/.face': No such file or directory

(polkit-gnome-authentication-agent-1:14900): polkit-gnome-1-WARNING **: 11:15:05.787: Couldn't open user icon: Failed to open file '/home/test/.face': No such file or directory
Gtk-Message: 11:15:05.792: GtkDialog mapped without a transient parent. This is discouraged.

(Thunar:14894): Gdk-WARNING **: 11:15:09.888: gdk_window_set_icon_list: icons too large

(gedit:15290): Gtk-WARNING **: 11:15:28.975: Calling org.xfce.Session.Manager.Inhibit failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "Inhibit" with signature "susu" on interface "org.xfce.Session.Manager" doesn't exist


(Thunar:14894): Gdk-WARNING **: 11:25:15.957: gdk_window_set_icon_list: icons too large

(Thunar:14894): Gdk-WARNING **: 11:25:50.724: gdk_window_set_icon_list: icons too large

(Thunar:14894): Gdk-WARNING **: 11:43:21.841: gdk_window_set_icon_list: icons too large

(Thunar:14894): Gdk-WARNING **: 11:43:32.007: gdk_window_set_icon_list: icons too large
Xlib:  extension "XINERAMA" missing on display ":4.0".
func=xmlSecCheckVersionExt:file=xmlsec.c:line=188:obj=unknown:subj=unknown:error=19:invalid version:mode=abi compatible;expected minor version=2;real minor version=2;expected subminor version=25;real subminor version=26

(soffice:26999): GLib-GObject-WARNING **: 11:43:49.549: ../../../../gobject/gsignal.c:3492: signal name 'selection_changed' is invalid for instance '0x556b63f812c0' of type 'OOoAtkObjCompTxt'
func=xmlSecCheckVersionExt:file=xmlsec.c:line=188:obj=unknown:subj=unknown:error=19:invalid version:mode=abi compatible;expected minor version=2;real minor version=2;expected subminor version=25;real subminor version=26

(Thunar:14894): Gdk-WARNING **: 11:44:08.894: gdk_window_set_icon_list: icons too large

(Thunar:14894): Gdk-WARNING **: 11:46:22.158: gdk_window_set_icon_list: icons too large

(tracker-miner-fs:14902): Tracker-CRITICAL **: 11:50:05.553:   (Sparql buffer) Error in task 1 (file:///home/is28/konnov28/python2) of the array-update: Subject `urn:uuid:6414ec05-9011-532c-b9a5-b4b198f3fcae' is not in domain `nfo:FileDataObject' of property `nfo:fileName'

(tracker-miner-fs:14902): Tracker-CRITICAL **: 11:50:05.553: Could not execute sparql: Subject `urn:uuid:6414ec05-9011-532c-b9a5-b4b198f3fcae' is not in domain `nfo:FileDataObject' of property `nfo:fileName'
/usr/lib/ubuntu-release-upgrader/check-new-release-gtk:30: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
WARNING:root:timeout reached, exiting

Fri Dec 13 12:43:24 2019
 Connections: closed: 0.0.0.0::50579 (Clean disconnection)
 SMsgWriter:  framebuffer updates 7446
 SMsgWriter:    copyRect rects 7023, bytes 112368
 SMsgWriter:    hextile rects 25766, bytes 88994557
 SMsgWriter:    raw bytes equivalent 934271784, compression ratio 10.498078

(tracker-miner-fs:14902): GLib-GObject-WARNING **: 13:57:39.640: g_object_notify: object class 'UpClient' has no property named 'g-name-owner'

(tracker-miner-fs:14902): GLib-GObject-WARNING **: 13:57:39.640: g_object_notify: object class 'UpDevice' has no property named 'g-name-owner'

Received signal:15->'Terminated'

(x-terminal-emulator:26829): libxfce4ui-WARNING **: 13:57:39.865: ICE I/O Error

(x-terminal-emulator:26829): libxfce4ui-WARNING **: 13:57:39.865: Disconnected from session manager.

Received signal:15->'Terminated'

OK

xfce4-panel: Fatal IO error 4 (Interrupted system call) on X server :4.0.
xfwm4: Fatal IO error 4 (Interrupted system call) on X server :4.0.
xfdesktop: Fatal IO error 11 (Resource temporarily unavailable) on X server :4.0.
