
Xvnc Free Edition 4.1.1 - built Feb 25 2015 23:02:21
Copyright (C) 2002-2005 RealVNC Ltd.
See http://www.realvnc.com for information on VNC.
Underlying X server release 40300000, The XFree86 Project, Inc


Wed Nov 27 11:51:35 2019
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on port 5902
 vncext:      created VNC server for screen 0
error opening security policy file /etc/X11/xserver/SecurityPolicy
Could not init font path element /usr/X11R6/lib/X11/fonts/Type1/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/Speedo/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/misc/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/75dpi/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/100dpi/, removing from list!
Could not init font path element /usr/share/fonts/X11/75dpi/, removing from list!
Could not init font path element /usr/share/fonts/X11/100dpi/, removing from list!
xrdb: No such file or directory
xrdb: can't open file '/home/is28/lobanov28/.Xresources'
/usr/bin/startxfce4: X server already running on display :2
gpg-agent[4556]: WARNING: "--write-env-file" is an obsolete option - it has no effect
gpg-agent: a gpg-agent is already running - not starting a new one

(xfce4-session:4545): xfce4-session-WARNING **: 11:51:38.981: gpg-agent returned no PID in the variables

(xfce4-session:4545): xfce4-session-WARNING **: 11:51:38.987: xfsm_manager_load_session: Something wrong with /home/is28/lobanov28/.cache/sessions/xfce4-session-virt-1:2, Does it exist? Permissions issue?

(xfwm4:4560): xfwm4-WARNING **: 11:51:39.008: The display does not support the XRender extension.

(xfwm4:4560): xfwm4-WARNING **: 11:51:39.008: The display does not support the XComposite extension.

(xfwm4:4560): xfwm4-WARNING **: 11:51:39.008: The display does not support the XDamage extension.

(xfwm4:4560): xfwm4-WARNING **: 11:51:39.008: The display does not support the XFixes extension.

(xfwm4:4560): xfwm4-WARNING **: 11:51:39.008: Compositing manager disabled.
(uint32 1,)
xfwm4-Message: 11:51:39.067: Unsupported keyboard modifier '<Super>Tab'

** (light-locker:4569): ERROR **: 11:51:39.084: Environment variable XDG_SESSION_PATH not set. Is LightDM running?

(polkit-gnome-authentication-agent-1:4576): GLib-CRITICAL **: 11:51:39.097: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:4576): polkit-gnome-1-WARNING **: 11:51:39.098: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

(xfsettingsd:4570): xfsettingsd-CRITICAL **: 11:51:39.168: RANDR extension is too old, version 1.1. Display settings won't be applied.
Xlib:  extension "XInputExtension" missing on display ":2.0".

(xfsettingsd:4570): xfsettingsd-CRITICAL **: 11:51:39.170: XI is not present.

(xfsettingsd:4570): xfsettingsd-CRITICAL **: 11:51:39.170: Failed to initialize the Xkb extension.

(xfsettingsd:4570): xfsettingsd-CRITICAL **: 11:51:39.171: Failed to initialize the Accessibility extension.

(nm-applet:4663): Gtk-WARNING **: 11:51:39.225: Can't set a parent on widget which has a parent
xfwm4-Message: 11:51:39.252: Unsupported keyboard modifier '<Super>Tab'

(nm-applet:4663): Gdk-CRITICAL **: 11:51:39.407: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

Wed Nov 27 11:51:44 2019
 Connections: accepted: 0.0.0.0::50154
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)

Wed Nov 27 11:51:47 2019
 VNCSConnST:  Server default pixel format depth 16 (16bpp) little-endian rgb565
 VNCSConnST:  Client pixel format depth 16 (16bpp) little-endian rgb565
/usr/lib/python3/dist-packages/blueman/plugins/applet/AppIndicator.py:8: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as girAppIndicator
ERROR:dbus.proxies:Introspect error on org.bluez:/org/bluez: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.553" (uid=1276 pid=4640 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)
ERROR:dbus.proxies:Introspect error on org.bluez:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.553" (uid=1276 pid=4640 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)
ERROR:dbus.proxies:Introspect error on org.bluez:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.553" (uid=1276 pid=4640 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)

(blueman-applet:4640): Gdk-CRITICAL **: 11:52:03.840: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

(Thunar:4566): Gdk-WARNING **: 11:52:13.463: gdk_window_set_icon_list: icons too large
Xlib:  extension "XINERAMA" missing on display ":2.0".
func=xmlSecCheckVersionExt:file=xmlsec.c:line=188:obj=unknown:subj=unknown:error=19:invalid version:mode=abi compatible;expected minor version=2;real minor version=2;expected subminor version=25;real subminor version=26

(tracker-miner-fs:4578): Tracker-CRITICAL **: 11:55:44.849:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/223.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 11:55:44.849: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 11:56:53.642:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/223.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 11:56:53.642: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 11:57:04.346:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/223.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 11:57:04.346: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 11:57:37.354:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/223.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 11:57:37.354: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 11:59:15.708:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/223.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 11:59:15.708: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(Thunar:4566): Gdk-WARNING **: 11:59:47.723: gdk_window_set_icon_list: icons too large
func=xmlSecCheckVersionExt:file=xmlsec.c:line=188:obj=unknown:subj=unknown:error=19:invalid version:mode=abi compatible;expected minor version=2;real minor version=2;expected subminor version=25;real subminor version=26

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:04:12.060:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/223.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:04:12.060: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:04:38.858:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/223.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:04:38.858: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:05:04.179:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/223.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:05:04.179: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:05:13.427:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/223.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:05:13.427: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:05:29.716:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/223.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:05:29.716: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:05:54.908:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/223.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:05:54.908: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:06:09.088:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/223.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:06:09.088: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:07:25.326:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/223.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:07:25.326: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:07:36.140:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/223.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:07:36.140: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:07:45.509:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/223.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:07:45.509: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:08:24.016:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/223.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:08:24.016: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:09:04.094:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/223.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:09:04.094: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:09:23.631:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/223.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:09:23.631: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:09:48.455:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/223.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:09:48.455: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:10:10.824:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/223.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:10:10.824: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:30:01.423:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/223.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:30:01.423: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:32:12.277:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/223.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:32:12.277: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:33:04.000:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/223.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:33:04.001: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:34:28.467:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/ww1.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:34:28.467: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:34:58.379:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/ww1.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:34:58.379: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:35:08.147:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/ww1.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:35:08.147: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:35:18.403:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/ww1.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:35:18.403: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:35:33.595:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/ww1.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:35:33.595: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:36:01.792:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/ww1.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:36:01.792: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:36:13.352:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/ww1.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:36:13.352: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:36:20.879:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/ww1.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:36:20.880: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:36:39.263:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/ww1.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:36:39.263: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

Wed Nov 27 12:43:57 2019
 Connections: closed: 0.0.0.0::50154 (Clean disconnection)
 SMsgWriter:  framebuffer updates 11742
 SMsgWriter:    copyRect rects 700, bytes 11200
 SMsgWriter:    hextile rects 52205, bytes 109529718
 SMsgWriter:    raw bytes equivalent 887533642, compression ratio 8.103131
xfce4-session: Fatal IO error 11 (Resource temporarily unavailable) on X server :2.

(xfsettingsd:4570): libxfce4ui-WARNING **: 11:27:39.014: ICE I/O Error

(xfsettingsd:4570): libxfce4ui-WARNING **: 11:27:39.014: Disconnected from session manager.

(xfce4-terminal:6458): libxfce4ui-WARNING **: 11:27:39.015: ICE I/O Error

(xfce4-terminal:6458): libxfce4ui-WARNING **: 11:27:39.015: Disconnected from session manager.
xfwm4: Fatal IO error 11 (Resource temporarily unavailable) on X server :2.0.

(xfce4-panel:4564): libxfce4ui-WARNING **: 11:27:39.017: ICE I/O Error

(xfce4-panel:4564): libxfce4ui-WARNING **: 11:27:39.017: Disconnected from session manager.

(xfdesktop:4568): libxfce4ui-WARNING **: 11:27:39.017: ICE I/O Error

(xfdesktop:4568): libxfce4ui-WARNING **: 11:27:39.017: Disconnected from session manager.
Thunar: Fatal IO error 11 (Resource temporarily unavailable) on X server :2.0.
xfsettingsd: Fatal IO error 11 (Resource temporarily unavailable) on X server :2.0.
Gdk-Message: 11:27:39.084: update-notifier: Fatal IO error 11 (Resource temporarily unavailable) on X server :2.0.

xfce4-panel: Fatal IO error 11 (Resource temporarily unavailable) on X server :2.0.
Gdk-Message: 11:27:39.090: polkit-gnome-authentication-agent-1: Fatal IO error 11 (Resource temporarily unavailable) on X server :2.0.

wrapper-1.0: Fatal IO error 11 (Resource temporarily unavailable) on X server :2.0.
Gdk-Message: 11:27:39.098: nm-applet: Fatal IO error 11 (Resource temporarily unavailable) on X server :2.0.

xfdesktop: Fatal IO error 11 (Resource temporarily unavailable) on X server :2.0.
wrapper-1.0: Fatal IO error 11 (Resource temporarily unavailable) on X server :2.0.
Gdk-Message: 11:27:39.177: blueman-applet: Fatal IO error 11 (Resource temporarily unavailable) on X server :2.0.

X IO Error
Gdk-Message: 11:27:39.179: evolution-alarm-notify: Fatal IO error 11 (Resource temporarily unavailable) on X server :2.0.

Gdk-Message: 11:27:39.181: gedit: Fatal IO error 11 (Resource temporarily unavailable) on X server :2.0.

Gdk-Message: 11:27:39.192: xfce4-terminal: Fatal IO error 11 (Resource temporarily unavailable) on X server :2.0.

/usr/share/system-config-printer/applet.py:45: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
system-config-printer-applet: failed to start NewPrinterNotification service
system-config-printer-applet: failed to start PrinterDriversInstaller service: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.552" is not allowed to own the service "com.redhat.PrinterDriversInstaller" due to security policies in the configuration file
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 11 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 15 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 16 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 20 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 22 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 24 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 25 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 29 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 33 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 34 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 38 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 40 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 44 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 48 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 50 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 54 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 55 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 59 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 61 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 63 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 67 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 69 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 73 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 75 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 79 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 81 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 85 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 86 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 90 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 94 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 96 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 98 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 100 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 104 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 106 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 110 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 111 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 115 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 117 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 119 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 123 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 125 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 129 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 130 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 134 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 136 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 137 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 141 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 143 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 144 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 148 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 150 was not found when attempting to remove it
  GLib.source_remove (self.timer)

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:27:10.231:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/ww1.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:27:10.238: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:27:28.746:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/ww1.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:27:28.746: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:33:55.644:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/ww1.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:33:55.644: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:34:14.926:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/ww1.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:4578): Tracker-CRITICAL **: 12:34:14.926: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 152 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 156 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 157 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 161 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 163 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 164 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 168 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 170 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 171 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 173 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 174 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 176 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 178 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 180 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 181 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 185 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 187 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 188 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 192 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 194 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 196 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 200 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 202 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 208 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 212 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 213 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 219 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 220 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 224 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 226 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 228 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 232 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 233 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 237 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 239 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 240 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 244 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 248 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 249 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 257 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 261 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 262 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 266 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 270 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 274 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 275 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 283 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 284 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 288 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 290 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 291 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 295 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 297 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 301 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 302 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:358: Warning: Source ID 306 was not found when attempting to remove it
  GLib.source_remove (self.timer)
