
Xvnc Free Edition 4.1.1 - built Feb 25 2015 23:02:21
Copyright (C) 2002-2005 RealVNC Ltd.
See http://www.realvnc.com for information on VNC.
Underlying X server release 40300000, The XFree86 Project, Inc


Fri Nov  1 11:43:46 2019
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on port 5913
 vncext:      created VNC server for screen 0
error opening security policy file /etc/X11/xserver/SecurityPolicy
Could not init font path element /usr/X11R6/lib/X11/fonts/Type1/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/Speedo/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/misc/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/75dpi/, removing from list!
Could not init font path element /usr/X11R6/lib/X11/fonts/100dpi/, removing from list!
Could not init font path element /usr/share/fonts/X11/75dpi/, removing from list!
Could not init font path element /usr/share/fonts/X11/100dpi/, removing from list!
xrdb: No such file or directory
xrdb: can't open file '/home/is28/lobanov28/.Xresources'
/usr/bin/startxfce4: X server already running on display :13
gpg-agent[10416]: WARNING: "--write-env-file" is an obsolete option - it has no effect
gpg-agent: a gpg-agent is already running - not starting a new one

(xfce4-session:10406): xfce4-session-WARNING **: 11:43:49.210: gpg-agent returned no PID in the variables

(xfce4-session:10406): xfce4-session-WARNING **: 11:43:49.261: xfsm_manager_load_session: Something wrong with /home/is28/lobanov28/.cache/sessions/xfce4-session-virt-1:13, Does it exist? Permissions issue?

(xfwm4:10420): xfwm4-WARNING **: 11:43:49.285: The display does not support the XRender extension.

(xfwm4:10420): xfwm4-WARNING **: 11:43:49.286: The display does not support the XComposite extension.

(xfwm4:10420): xfwm4-WARNING **: 11:43:49.286: The display does not support the XDamage extension.

(xfwm4:10420): xfwm4-WARNING **: 11:43:49.286: The display does not support the XFixes extension.

(xfwm4:10420): xfwm4-WARNING **: 11:43:49.286: Compositing manager disabled.

** (light-locker:10429): ERROR **: 11:43:49.314: Environment variable XDG_SESSION_PATH not set. Is LightDM running?

(polkit-gnome-authentication-agent-1:10431): GLib-CRITICAL **: 11:43:49.337: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:10431): polkit-gnome-1-WARNING **: 11:43:49.338: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
xfwm4-Message: 11:43:49.352: Unsupported keyboard modifier '<Super>Tab'
(uint32 1,)

(xfsettingsd:10433): xfsettingsd-CRITICAL **: 11:43:49.462: RANDR extension is too old, version 1.1. Display settings won't be applied.
Xlib:  extension "XInputExtension" missing on display ":13.0".

(xfsettingsd:10433): xfsettingsd-CRITICAL **: 11:43:49.465: XI is not present.

(xfsettingsd:10433): xfsettingsd-CRITICAL **: 11:43:49.465: Failed to initialize the Xkb extension.

(xfsettingsd:10433): xfsettingsd-CRITICAL **: 11:43:49.465: Failed to initialize the Accessibility extension.
xfwm4-Message: 11:43:49.528: Unsupported keyboard modifier '<Super>Tab'

(nm-applet:10545): Gtk-WARNING **: 11:43:49.644: Can't set a parent on widget which has a parent

(wrapper-1.0:10584): Gdk-WARNING **: 11:43:49.779: /build/gtk+2.0-AoeliP/gtk+2.0-2.24.32/gdk/x11/gdkdrawable-x11.c:952 drawable is not a pixmap or window

(nm-applet:10545): Gdk-CRITICAL **: 11:43:49.788: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

Fri Nov  1 11:43:53 2019
 Connections: accepted: 0.0.0.0::51571
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)

Fri Nov  1 11:43:57 2019
 VNCSConnST:  Server default pixel format depth 16 (16bpp) little-endian rgb565
 VNCSConnST:  Client pixel format depth 16 (16bpp) little-endian rgb565
/usr/lib/python3/dist-packages/blueman/plugins/applet/AppIndicator.py:8: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as girAppIndicator
ERROR:dbus.proxies:Introspect error on org.bluez:/org/bluez: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.473" (uid=1276 pid=10531 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)
ERROR:dbus.proxies:Introspect error on org.bluez:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.473" (uid=1276 pid=10531 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)
ERROR:dbus.proxies:Introspect error on org.bluez:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.473" (uid=1276 pid=10531 comm="/usr/bin/python3 /usr/bin/blueman-applet " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (bus)

(wrapper-1.0:10584): Gdk-WARNING **: 11:44:04.562: /build/gtk+2.0-AoeliP/gtk+2.0-2.24.32/gdk/x11/gdkdrawable-x11.c:952 drawable is not a pixmap or window

(Thunar:10426): Gdk-WARNING **: 11:44:42.232: gdk_window_set_icon_list: icons too large

(Thunar:10426): Gdk-WARNING **: 11:44:53.014: gdk_window_set_icon_list: icons too large

(Thunar:10426): Gdk-WARNING **: 11:45:40.317: gdk_window_set_icon_list: icons too large
Xlib:  extension "XINERAMA" missing on display ":13.0".
func=xmlSecCheckVersionExt:file=xmlsec.c:line=188:obj=unknown:subj=unknown:error=19:invalid version:mode=abi compatible;expected minor version=2;real minor version=2;expected subminor version=25;real subminor version=26
func=xmlSecCheckVersionExt:file=xmlsec.c:line=188:obj=unknown:subj=unknown:error=19:invalid version:mode=abi compatible;expected minor version=2;real minor version=2;expected subminor version=25;real subminor version=26

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:50:14.291:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/z2.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:50:14.291: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:50:44.334:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/z2.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:50:44.334: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:51:04.681:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/z2.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:51:04.681: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:51:05.256:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/z2.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:51:05.256: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:55:35.574:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/z2.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:55:35.574: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:55:49.508:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/z2.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:55:49.508: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:56:12.448:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/z2.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:56:12.448: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:56:40.695:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/z2.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:56:40.695: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:56:57.812:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/z2.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:56:57.812: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:57:06.143:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/z2.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:57:06.143: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:58:39.844:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/z2.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:58:39.845: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:58:59.610:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/z2.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 11:58:59.610: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 12:13:11.794:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/z2.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 12:13:11.794: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 12:13:24.137:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/z2.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 12:13:24.137: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 12:18:07.416:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/z2.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 12:18:07.416: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 12:18:22.990:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/z2.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 12:18:22.990: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 12:19:08.315:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/z2.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 12:19:08.315: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 12:19:18.650:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/z2.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 12:19:18.650: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 12:20:49.107:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/z2.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 12:20:49.107: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 12:26:31.229:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/z2.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 12:26:31.229: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 12:29:41.119:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/z2.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 12:29:41.119: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 12:30:55.241:   (Sparql buffer) Error in task 0 (file:///home/is28/lobanov28/z2.py) of the array-update: UNIQUE constraint failed: nie:DataObject.nie:url

(tracker-miner-fs:10434): Tracker-CRITICAL **: 12:30:55.241: Could not execute sparql: UNIQUE constraint failed: nie:DataObject.nie:url

(Thunar:10426): Gdk-WARNING **: 12:31:33.471: gdk_window_set_icon_list: icons too large

Fri Nov  1 12:43:30 2019
 Connections: closed: 0.0.0.0::51571 (Clean disconnection)
 SMsgWriter:  framebuffer updates 9183
 SMsgWriter:    copyRect rects 2784, bytes 44544
 SMsgWriter:    hextile rects 26261, bytes 73998760
 SMsgWriter:    raw bytes equivalent 682965308, compression ratio 9.229416

(xfdesktop:10428): libxfce4ui-WARNING **: 13:37:03.353: ICE I/O Error

(xfdesktop:10428): libxfce4ui-WARNING **: 13:37:03.463: Disconnected from session manager.
xfwm4: Fatal IO error 11 (Resource temporarily unavailable) on X server :13.0.
xfdesktop: Fatal IO error 25 (Inappropriate ioctl for device) on X server :13.0.
